server:
    port: 8080

spring:
    datasource:
        url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/db_example
        username: springuser1
        password: springpassword
        driver-class-name: com.mysql.cj.jdbc.Driver
    jpa:
        hibernate:
            ddl-auto: update


jwt:
    secret: NU1q4U5Xti95yshyUPVjWL2fiKIp2KYo7BoeYVkRL2Q=
    expiration: 36000000

logging:
    level:
        org.springframework.security: trace
